### ISSUE TITLE
Library shouldn't include "allowBackup"

### ISSUE THREAD

**Issue by esqi** [veritrans/veritrans-android#119]
Attribute application@allowBackup value=(false) from AndroidManifest.xml:49:9-36
        is also present at [id.co.veritrans:coreflow:0.10.11-SANDBOX] AndroidManifest.xml:12:9-35 value=(true).
        Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:47:5-319:19 to override.

**Comment by rakawestu** [comment]
Hi @esqi. Thanks for your suggestion.

Currently we're working to replace current infrastructure for mobile SDK into [Snap](https://snap-docs.herokuapp.com/) instead of using VT-Direct. 

Unfortunately we won't update the current SDK because we will release a new SDK with easier usage and minimal dependencies. But your suggestion is implemented in our new SDK so you can use it on our new SDK .

**Comment by adiputrastwn** [comment]
Hi @rakawestu 

When the new SDK will be released? And Tcash payment is already included in this update?

**Comment by rakawestu** [comment]
Hi @adiputrastwn . 
We are finalizing the release this week. So expect by end of this week the new SDK is ready to use.
